"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_controller_1 = require("../controllers/user.controller");
const userRouter = (0, express_1.Router)();
userRouter.get('/', user_controller_1.getUsers);
userRouter.delete('/:id', user_controller_1.deleteUserId);
userRouter.put('/:id', user_controller_1.updateUser);
userRouter.post('/', user_controller_1.createUser);
exports.default = userRouter;
